### ISSUE TITLE
今日の日付と異なるファイルが開かれる

### ISSUE THREAD

**Issue by eastxe** [hitode909/atom-open-daily-memo#3]
こんにちは。
素晴らしいパッケージの公開ありがとうございます。

毎日便利に使っていたのですが、
今日のAM8:00に今日の日付.mdを開こうとしたところ、昨日の日付.mdが開かれました。

開く日付をJSTではなくUTCで決めているようです。
意図的にそうしているのでしたらすみません。

**Comment by hitode909** [comment]
こんにちは，報告ありがとうございます，朝8時に使ったことがなく気付いていませんでした．
現地の時刻を使うようにすればよさそうですね．

**Comment by hitode909** [comment]
遅くなりましたが修正しました! 0.3.0としてリリース済です
https://atom.io/packages/atom-open-daily-memo
